fix: switch gdk crate to gdk4
hyprutils/hyprwall pull request #46
Opened 2024-11-04 23:48 UTC by arminius-smh

Helloo,

I wanted to package this project for nix and noticed that the built failed with:
```The system library `gdk-3.0` required by crate `gdk-sys` was not found.```

It seems like the rust crate gdk, which is for gdk 3 bindings https://crates.io/crates/gdk should instead be the gdk4 crate https://crates.io/crates/gdk4, so right now gtk3 would also be needed as a dependency

So the only thing I've done is 
```sh
cargo remove gdk
cargo add gdk4
```
and now hyprwall can be built with only gtk4 as a dependency!

2024-11-04 23:53 UTC, adamperkowski commented
We shouldn't even be using `gdk` or `gio` packages in the first place. They are already bundled in `gtk`. What happened there @nnyyxxxx ?

2024-11-04 23:58 UTC, arminius-smh commented
> We shouldn't even be using `gdk` or `gio` deps in the first place. They are already bundled in `gtk`. What happened there @nnyyxxxx ?

Ah okay, I wasn't sure if there was a specific reason for it, want me to remove both of these dependencies in this pr?

btw, hyprlauncher also has a gio dependency on its own

2024-11-04 23:59 UTC, adamperkowski requested changes
like this

2024-11-04 23:59 UTC, adamperkowski commented on Cargo.toml
> +gdk4 = "0.9.3"
```suggestion
```

2024-11-04 23:59 UTC, adamperkowski commented on Cargo.toml
>  gio = "0.18.0"
```suggestion
```

2024-11-04 23:59 UTC, adamperkowski commented
> btw, hyprlauncher also has a gio dependency on its own

yeah we should fix that up too

2024-11-04 23:59 UTC, nnyyxxxx commented
> We shouldn't even be using `gdk` or `gio` deps in the first place. They are already bundled in `gtk`. What happened there @nnyyxxxx ?

im dumb

2024-11-05 00:01 UTC, nnyyxxxx approved these changes

2024-11-05 00:01 UTC, merged

2024-11-05 00:01 UTC, adamperkowski commented
Thanks